### Import required modules

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.linear_model import LinearRegression, Lasso
from sklearn.metrics import (
    accuracy_score, mean_absolute_error, mean_squared_error, root_mean_squared_error, r2_score
    
)
from sklearn.preprocessing import StandardScaler

## Load all dataset using pyhon

In [3]:
train_df = pd.read_csv("./datasets/train.csv")
val_df = pd.read_csv("./datasets/val.csv")
test_df = pd.read_csv("./datasets/test.csv")

train_df.head()

   Year  dengue_total  ... avg_snowfall avg_precipitation
0  2024             0  ...         none              high
1  2022             0  ...         none          moderate
2  2024            19  ...         none               low
3  2022             1  ...        light               low
4  2022             0  ...         none              high

[5 rows x 17 columns]

## Use only selected features for linear regression

In [4]:
# selected columns
selected_columns = [
    "Year",
    "dengue_total",
    "Location",
    "Month",
    "monthly_avg_temperature",
    "avg_daily_rain",
    "avg_daily_humidity",
    "avg_daily_soil_moisture",
    "avg_daily_soil_temperature",
    "avg_daily_snowfall",
    "avg_daily_precipitation"
]

# dataset with only selected columns
train = train_df[selected_columns]
val = val_df[selected_columns]
test = test_df[selected_columns]

# get dummies of required data
train_loc = pd.get_dummies(train["Location"], dtype=int)
train_month = pd.get_dummies(train["Month"], dtype=int)

test_loc = pd.get_dummies(test["Location"], dtype=int)
test_month = pd.get_dummies(test["Month"], dtype=int)

val_loc = pd.get_dummies(val["Location"], dtype=int)
val_month = pd.get_dummies(val["Month"], dtype=int)

# Final dataset ready to be used for train, val and testing
train = pd.concat([train.drop(columns=["Month", "Location"]), train_loc, train_month], axis=1)
val = pd.concat([val.drop(columns=["Month", "Location"]), val_loc, val_month], axis=1)
test = pd.concat([test.drop(columns=["Month", "Location"]), test_loc, test_month], axis=1)

# display to see basic structure
print("Train Set")
display(train.head(3))
print("Val Set")
display(val.head(3))
print("Test Set")
display(test.head(3))

Train Set

   Year  dengue_total  monthly_avg_temperature  ...  Nov  Oct  Sep
0  2024             0                10.223880  ...    0    0    0
1  2022             0                30.428612  ...    0    0    0
2  2024            19                10.010685  ...    0    0    1

[3 rows x 90 columns]

Val Set

   Year  dengue_total  monthly_avg_temperature  ...  Nov  Oct  Sep
0  2023             2                10.692419  ...    0    0    0
1  2023             0                28.076279  ...    0    0    0
2  2023             1                28.192223  ...    0    0    0

[3 rows x 90 columns]

Test Set

   Year  dengue_total  monthly_avg_temperature  ...  Nov  Oct  Sep
0  2023             0                22.582495  ...    0    0    0
1  2024            55                10.086084  ...    0    0    1
2  2024             4                10.825872  ...    0    0    0

[3 rows x 90 columns]

# Extract X and Y from data

In [5]:
# Extract train and test
X_train = train.drop(columns=["dengue_total"])
y_train = train["dengue_total"]

X_val = val.drop(columns=["dengue_total"])
y_val = val["dengue_total"]

X_test = test.drop(columns=["dengue_total"])
y_test = test["dengue_total"]